export const tech = [
  {
    img:'../../assets/img/html.png',
    name:'Html',
  },
  {
    img:'../../assets/img/css.png',
    name:'CSS',
  },
  {
    img:'../../assets/img/sass.png',
    name:'SASS',
  },
  {
    img:'../../assets/img/js.png',
    name:'JavaScript',
  },
  {
    img:'../../assets/img/ts.png',
    name:'TypeScript',
  },
  {
    img:'../../assets/img/angular.png',
    name:'Angular',
  },
  {
    img:'../../assets/img/vue.png',
    name:'Vue.js',
  },
  {
    img:'../../assets/img/bootstrap.png',
    name:'Bootstrap',
  },
  {
    img:'../../assets/img/axios.png',
    name:'Axios',
  },
  {
    img:'../../assets/img/firebase.png',
    name:'Firebase',
  },
  {
    img:'../../assets/img/git.png',
    name:'Git',
  },
  {
    img:'../../assets/img/npm.png',
    name:'npm',
  },
  {
    img:'../../assets/img/node.png',
    name:'Node',
  },
  {
    img:'../../assets/img/php.png',
    name:'PHP',
  },
  {
    img:'../../assets/img/Laravel.png',
    name:'Laravel',
  },
  {
    img:'../../assets/img/mysql.svg',
    name:'MySQL',
  },
]
